"meshes":[{"name":"KC9BG19_Untitled.071"
"id":"KC9BG19_Untitled.071"
"materialId":"skyscraper_1.Multimaterial#0"
"billboardMode":0
"position":[0
0
0]
"rotation":[-1.5708
0
0]
"scaling":[1
1
1]
"isVisible":true
"freezeWorldMatrix":false
"isEnabled":true
"checkCollisions":false
"receiveShadows":false
"pickable":true
"tags":""
