,
"behavior":{
    [
        {
            "strategy":"select",
            "parameters":{
                
            }
        },
        {
            "strategy":"scale",
            "parameters":{
                "x":"4",
                "y":"7",
                "z":"0"
            }
        },
        {
             "strategy":"changeColorOnHover",
                "parameters":{
                    "color":"red"
                }
            }
        }
    ]
}